function Pessoa() {
	this.id = "";
	this.dataDeNascimento = "";
	this.nome = "";
	this.endLogradouro = "";
	this.endNumero = "";
	this.endBairro = "";
	this.endCidade = "";
	this.endUf = "";
	this.endCep = "";
	this.endComplemento = "";
	this.telefoneFixo = "";
	this.telefoneMovel = "";
	this.email = "";
	this.im = "";
	this.logUser = "";
	this.logDate = "";
	this.version = "";
}